[package]
name = "quest-04"
version = "0.1.0"
edition = "2021"

[features]
nightly = []

[dependencies]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
