[package]
name = "story-4-02"
version.workspace = true
edition.workspace = true

[package.metadata.everybody_codes]
event = 4
quest = 2

[dependencies]
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[build-dependencies]
everybody-codes.workspace = true

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
