[package]
name = "quest-16"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rayon = "1.10.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
