[package]
name = "quest-11"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
