[package]
name = "quest-18"
version = "0.1.0"
edition = "2021"

[dependencies]
bytecount = "0.6.8"
rayon = "1.10.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
