[package]
name = "story-2-03"
version.workspace = true
edition.workspace = true

[package.metadata.everybody_codes]
event = 2
quest = 3

[dependencies]

[dev-dependencies]
criterion.workspace = true

[build-dependencies]
everybody-codes.workspace = true

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
