[package]
name = "quest-07"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[dependencies]
rayon = "1.10.0"
