[package]
name = "quest-05"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.15.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
